#!/usr/bin/env bash
# Shebang for better file detection

BASE_ARCH="arm64"

# Keep for Bookworm template
DOWNLOAD_URL_CHECKSUM="https://dietpi.com/downloads/images/DietPi_RPi5-ARMv8-Bookworm.img.xz"
DOWNLOAD_URL_IMAGE="https://dietpi.com/downloads/images/DietPi_RPi5-ARMv8-Bookworm.img.xz.sha256"

# New locations after Bullseye turned into 'oldstable'
# DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.sha256"
# DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.torrent"


# export variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
